### ISSUE TITLE
checkpoint release

### ISSUE THREAD

**Issue by ChuhuaW** [KeenyJin/SOIA-DOD#1]
Hey there,

Thanks for sharing your work. I was wondering if you also plan on releasing the checkpoints?

I followed the instructions and got the following results on the ego4d v2 validation set:

Box + Noun mAP: 30.67
Box + Noun + Verb mAP: 14.70
Box + Noun + TTC mAP: 9.21
Box + Noun + Verb + TTC mAP: 4.89

Are these results expected? Thank you.

**Comment by KeenyJin** [comment]
Hi @ChuhuaW 

1. This is the [checkpoint](https://drive.google.com/file/d/1V4AV9YCb257UmP76Ox1FUp1d7Dlm6Iab/view?usp=sharing) for my final challenge submission.

2. Your results seem consistent with what I observed during my participation in the challenge. There was a notable discrepancy between the validation and test set results, with the latter generally being higher. Keep in mind that at inference, results can vary depending on `yolo_max_det` and `top_k_verb` even when using the same checkpoint.

Please let me know if there are any other problems :)

**Comment by ChuhuaW** [comment]
@KeenyJin Thank you so much!
